[package]
name = "rust_logger"
version = "0.1.0"
edition = "2021"

[dependencies]
aes-gcm = "0.10"              # AES-GCM encryption
rand = "0.8"                  # Secure random key/nonce
base64 = "0.21"               # For storing keys
hex = "0.4"                   # Optional: hex output
